// <auto-generated />
using System;
using CalculadoraHerreria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculadoraHerreria.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CalculadoraHerreria.Models.Configuracion", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Clave");

                    b.ToTable("Configuraciones");
                });

            modelBuilder.Entity("CalculadoraHerreria.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Ancho")
                        .HasColumnType("REAL");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimensiones")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Espesor")
                        .HasColumnType("REAL");

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Forma")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double?>("LargoDisponible")
                        .HasColumnType("REAL");

                    b.Property<string>("MaterialBase")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadOriginal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Condicion");

                    b.HasIndex("Familia");

                    b.HasIndex("Forma");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("CalculadoraHerreria.Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadAnterior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadPosterior")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("SobranteMm")
                        .HasColumnType("REAL");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("MaterialId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("CalculadoraHerreria.Models.Plantilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plantillas");
                });

            modelBuilder.Entity("CalculadoraHerreria.Models.PlantillaPieza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionUso")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("LargoMm")
                        .HasColumnType("REAL");

                    b.Property<int>("PlantillaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlantillaId");

                    b.ToTable("PlantillaPiezas");
                });

            modelBuilder.Entity("CalculadoraHerreria.Models.Movimiento", b =>
                {
                    b.HasOne("CalculadoraHerreria.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("CalculadoraHerreria.Models.PlantillaPieza", b =>
                {
                    b.HasOne("CalculadoraHerreria.Models.Plantilla", "Plantilla")
                        .WithMany("Piezas")
                        .HasForeignKey("PlantillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plantilla");
                });

            modelBuilder.Entity("CalculadoraHerreria.Models.Plantilla", b =>
                {
                    b.Navigation("Piezas");
                });
#pragma warning restore 612, 618
        }
    }
}
